### ISSUE TITLE
1.와 새글 작성 관련 오류

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-wa#1]
안녕하세요.
링크를 걸기가 애매한 내용이어서 풀어서 씁니다.

*새 글 등록 관련 이슈
-원래 새글 작성 후 등록을 누르면 등록된 화면이 보여지는데
-현재 새글 작성 후 등록하기를 누르면 해당 창에서 화면 변동이 없음(새글 등록이 안되는 줄 알고 여러번 눌러봄)
-아예 새 창을 열어서 페이지를 확인하니 글이 등록 됨(여러번 누룬 만큼 새글은 여러개 등록되어 있음)

*새 글 등록 후 메일 수신 건
-기존 웹진에 새 글이 올라가면 제 계정으로 메일이 오도록 되어 있습니다.
-현재(위의 오류가 발생한 이후) 새 글이 등록되었다는 메일이 오지 않고 있는데 이 부분도 오류가 발생한 것 같습니다.

당장 글 올리는데에 큰 문제는 없지만 기존에 발생하지 않던 내용이라 공유 드립니다.
확인 부탁드립니다.

**Comment by mozodev** [comment]
http://www.wasuwon.net/article
위 링크처럼 이슈에서도 새글을 등록할 수 있고, 다른 메뉴에서도 새글을 등록할 수 있는데
제가 확인해보니 쓰기 버튼을 클릭하면 입력 창이 잘 보이는데요. 
구체적으로 어느 메뉴에서 말씀하신 오류가 발생하는지 알려주세요.

메일은 아직 발송이 안되고 있는데 이번주중으로 전에 요청하신 이슈포함해서 작업하겠습니다.

**Comment by suwonedu** [comment]
글이 업로드가 안되는 상황은 아닙니다.
한 카테고리에서만 생기는 문제도 아니고요.
(이슈, 현장, 칼럼, 정보 카테고리 모두 동일하게 나타납니다.)

**
'쓰기 버튼>새글등록 화면>등록' 까지는 잘 돌아가고 그 이후가 문제인데요,
기존에는 등록 버튼을 누르면 '서버에 등록 중입니다'라는 문구가 나온 후 글이 업로드 된 화면으로 넘어갔습니다.
하지만 현재는 등록 버튼을 눌러도 '서버에 등록 중입니다' 문구만 뜨고 글쓰기 화면에 머물고 있습니다.
글이 업로드 된 화면으로 전환이 안되어 마치 새 글 등록이 안되는 것 처럼 보여집니다.

글쓰기 오류 동영상을 촬영해보았는데 용량이 크다고 해서 메일로 보내드렸습니다.
확인하시면 금방 이해가 되실 것 같습니다.

**Comment by suwonedu** [comment]
안녕하세요  :)

일전에 말씀드린 글쓰기 오류 건 수정 문의 드립니다.
다음 웹진 발행이 얼마 남지 않아서 진행이 어떻게 되고 있는지 궁금합니다.

확인 부탁드립니다.

**Comment by mozodev** [comment]
저번주에 설명드린 것처럼 xe 업그레이드가 완료되면 수정이 되는 문제인데...
누구나 학교 수정 건이 간단하지 않아서 시일이 좀 지체됐지만 이제 완료가 되서
몇 가지 문제만 더 해결하면 서버에 적용할 수 있습니다. 관련해서 제가 내일 중에 전화드리겠습니다.

**Comment by mozodev** [comment]
수정했습니다.
