### ISSUE TITLE
문의 - 글쓰기 창

### ISSUE THREAD

**Issue by suwonedu** [ictact-coop/suwonedu-wa#2]
안녕하세요

1.
글쓰기 창의 여러 옵션 들을 수정하신 걸로 아는데
기존에 있던 것이 없어지거나, 바뀐게 여럿 있는 것 같습니다.
그 중 삭제된 텍스트 붙임 버튼은 다시 생성해주시면 좋겠습니다.

익스플로러로 보는 웹진 화면과 크롬으로 보는 화면이 다릅니다.
각각의 속성이 다르니 조금씩 틀어지는 것은 알고 있었지만
이번 글쓰기 창 수정 이후의 게시물은 굉장히 많이 어긋나 있었어요.
제가 바로 확인 후 수정해서 지금은 괜찮지만 텍스트를 붙여넣을 때마다 익스플로러와 크롬을 
번갈아가면서 확인하기는 어려울 것 같습니다.

2.
사진 업로드 건입니다.
지금 사진을 드래그하면 커서가 있는 곳(본문)에 바로 사진이 가서 붙습니다.
기존대로 사진을 끌어다놓고 제가 원하는 곳에 필요한 사진을 넣는 방식으로 다시 수정 부탁드립니다.

3.
폰트 스타일 부분입니다.
예를 들어 글꼴의 comic sans체를 적용시키면 크롬환경에서는 그냥 명조로 적용되는데
익스플로러에서는 해당 폰트로 적용되어 보입니다.
이 부분 확인 부탁드립니다.

4.
표 만들기와 번호 매기기 등은 수정이 안되었습니다.
진짜 필요한 수정은 이 부분이라, 재확인 요청 드립니다.
그리고 새 글이 등록되면 메일이 오도록 조정 부탁드립니다.
(2월 20일에 공유드린 PPT 를 확인해주시면 감사하겠습니다.)

5.
어느 부분을 수정하셨는지에 대한 공유가 있으면 좋겠습니다.
제가 요청드리지 않은 부분들도 수정이 되어있어서요.(예를 들면 텍스트 붙임버튼 삭제, 컬러창 변화 등)
업로드는 제가 주로 하지만, 다른 분들도 글을 올립니다. 
특히 시니어 층이 사용할때가 있는데, 그분들께 기존의 환경에서 글올리는 방법을 
매뉴얼을 만들어 공지했기 때문에 변화된 부분에 대한 설명을 다시 해야 합니다.
(텍스트 붙임 버튼 이용이라던지, 컬러 같은것도 지정을 해드렸기 때문에
 색이 바뀌거나 하면 할아버지들이 혼돈의 카오스에 빠지는 ..... .)
요청드리지 않은 수정이 발생하면 그 분들께 다 다시 공지를 해야하는 번거로움이 있어요........

우선은 글쓰기 창 먼저 정리하고 
지난번에 문의드렸던 홈페이지 메인 부분 수정 > 모바일 버전 수정을 진행하면 좋을 것 같습니다.
메시지 확인 부탁드리며,
해당 건의 수정일정과 혹시 수정이 안된다면 이유도 함께 말씀해주시면 감사하겠습니다.

**Comment by mozodev** [comment]
네 적어주신 내용 검토하고 다시 알려드릴께요

**Comment by suwonedu** [comment]
안녕하세요 :)

글쓰기 창 수정 일정 공유 부탁드립니다.

**Comment by mozodev** [comment]
간단히 문자로 안내해드렸던 것처럼 제가 임의로 수정을 한 건 아니고 보안 업데이트하고 나서
전에 사용하시던 화면과 달라진 부분들인 것을 확인했습니다.

![old-write-form](https://user-images.githubusercontent.com/1661950/40594535-b9e3a16e-626a-11e8-82c9-45f5baf21c2e.png)

일단 위 화면처럼 예전 소스를 검토하면서 최대한 이전 상태로 돌리려고 작업을 하고 있고 
5월 31일 목요일에 확인하실 수 있게 작업을 완료하겠습니다.

**Comment by suwonedu** [comment]
안녕하세요 
혹시 몰라 오늘(6월 4일)에 새 글들을 등록하고 있습니다.
수정하고 계신 내용이 아직 적용되지는 않은 것 같습니다.

다 되시면 말씀해주세요.
(참, 새 글 업로드 / 댓글 등록 시 메일 알림 부분도 확인 부탁드립니다. )

**Comment by mozodev** [comment]
네 일단 수정된 부분만 서버에 반영했습니다.
